# Main settings for background components of Cinnamon
engine:
  # Enables debug mode (displays more technical details of the plugin)
  # Default value: false
  debug: false
  # UUID Map: A map containing player's UUID and their respective username
  uuid-map:
    # Should this feature be enabled?
    enabled: true
    # Update interval for the map (calculated in ticks)
    # Note that this task runs over hundreds to thousands of accounts per update
    # Default value: 1,200 (or around 60s)
    interval: 1200
  # Chunk map: A map containing all generated chunks on the server
  chunk-map:
    # Should this feature be enabled?
    enabled: true
    # Update interval for the map (calculated in ticks)
    # Note that this will read thousands of region files per update
    # Default value: 6,000 (or around 300s ~ 5 minutes)
    interval: 6000
    # Should we discard chunks with no containers/entities ?
    skip-empty-chunks: true